package PreviewProcessorTest.multipreview_function_with_two_previews_and_additional_preview_produces_three_snapshots.input

import PreviewProcessorTest.multipreview_function_with_two_previews_produces_two_snapshots.input.FontScalePreviews
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.runtime.Composable

@Preview
@FontScalePreviews
@Composable
fun MultiPreviewComposable() {
}
