package com.emergetools.android.standalone_preview_function_compiles_ok

import PreviewProcessorTest.multipreview_function_with_two_previews_produces_two_snapshots.input.FontScalePreviews
import androidx.compose.runtime.Composable

@FontScalePreviews
@Composable
fun MultiPreviewComposable() {
}
