name: distribution release deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-distribution:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "distribution-"
    if: ${{ startsWith(github.event.release.tag_name, 'distribution-') }}

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Sanity check distribution test
        run: ./gradlew :distribution:distribution:test :distribution:distribution:publishToMavenCentral -Dorg.gradle.parallel=false
