name: Gradle Plugin Release Deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-gradle-plugin:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "gradle-plugin-"
    if: ${{ startsWith(github.event.release.tag_name, 'gradle-plugin-') }}

    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Deploy plugin
        run: ./gradlew :gradle-plugin:plugin:publishPlugins
      - name: Deploy plugin to maven central
        run: ./gradlew :gradle-plugin:plugin:publishToMavenCentral --no-configuration-cache
