name: Gradle Plugin Checks

on:
  push:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
  pull_request:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check
        run: ./gradlew :gradle-plugin:plugin:check
        # If we build the plugin even just for testing we need the signing keys since they are required on non-snapshot builds
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
      - name: Archive test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Functional test reports
          path: '**/build/reports/tests/functionalTest'

