name: Gradle plugin release deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-gradle-plugin:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "gradle-plugin-"
    if: ${{ startsWith(github.event.release.tag_name, 'gradle-plugin-') }}

    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Deploy plugin
        run: ./gradlew :gradle-plugin:plugin:publishPlugins
