name: performance checks

on:
  push:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
      - performance/**
  pull_request:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
      - performance/**

jobs:

#  TODO: Ryan: Re-enable when build hang issue can be resolved.
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDKs
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: 17
#      - name: Run build
#        run: ./gradlew :performance:performance:build

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run unit tests
        run: ./gradlew :performance:performance:test
