name: Reaper release deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-reaper:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "reaper-"
    if: ${{ startsWith(github.event.release.tag_name, 'reaper-') }}

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Sanity check reaper test
        run: ./gradlew :reaper:reaper:test -Pandroid.useAndroidX=true
      - name: Deploy reaper
        run: ./gradlew :reaper:reaper:publishReleasePublicationToSonatypeStagingRepository -Pandroid.useAndroidX=true
