name: Reaper release deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-reaper:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "reaper-"
    if: ${{ startsWith(github.event.release.tag_name, 'reaper-') }}

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Sanity check reaper test
        run: ./gradlew :reaper:reaper:test :reaper:reaper:publishReleasePublicationToSonatypeStagingRepository -Dorg.gradle.parallel=false
