name: Reaper Snapshot Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-gradle-plugin:

    runs-on: ubuntu-latest

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Deploy plugin snapshot to Sonatype Snapshots
        run: ./gradlew :reaper:reaper:publishAllPublicationsToSonatypeSnapshotsRepo
