name: snapshots checks

on:
  push:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
      - snapshots/**
  pull_request:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
      - snapshots/**

jobs:

#  TODO: Ryan: Re-enable when build hang issue can be resolved.
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up JDKs
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'adopt'
#          java-version: 17
#      - name: Run build
#        run: ./gradlew :snapshots:snapshots:build -Pandroid.useAndroidX=true

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Run unit tests
        run: ./gradlew :snapshots:snapshots:test -Pandroid.useAndroidX=true
