name: snapshots sample app

on:
  # Intentionally run on all pushes to main branch to ensure we always have a base build with snapshots
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - gradle/**
      - gradle-plugin/**
      - snapshots/**

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Emerge snapshots
        run: ./gradlew :snapshots:sample:app:emergeUploadSnapshotBundleDebug -Pandroid.useAndroidX=true
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
