name: Sample App Snapshots

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: [ snapshots/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Emerge snapshots
        run: ./gradlew :snapshots:sample:app:emergeUploadSnapshotBundleDebug
        env:
          EMERGE_API_TOKEN: ${{ secrets.EMERGE_API_KEY }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
