name: Snapshots release deploy

on:
  release:
    types: [ published ]

jobs:
  deploy-snapshots:

    runs-on: ubuntu-latest

    # Only run when the tag begins with the string "snapshots-"
    if: ${{ startsWith(github.event.release.tag_name, 'snapshots-') }}

    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Sanity check snapshots test
        run: ./gradlew :snapshots:snapshots:test -Pandroid.useAndroidX=true
      - name: Sanity check snapshots-processor test
        run: ./gradlew :snapshots:snapshots-processor:test
      - name: Deploy snapshots
        run: ./gradlew :snapshots:snapshots:publishReleasePublicationToSonatypeStagingRepository -Pandroid.useAndroidX=true
      - name: Deploy snapshots-processor
        run: ./gradlew :snapshots:snapshots-processor:publishReleasePublicationToSonatypeStagingRepository
